// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCaloriecountingBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button buttonCallApi;

  @NonNull
  public final EditText editTextQuery;

  @NonNull
  public final TextView textViewResponse;

  @NonNull
  public final TextView textViewTitle;

  @NonNull
  public final TextView textViewTotalCalories;

  private ActivityCaloriecountingBinding(@NonNull RelativeLayout rootView,
      @NonNull Button buttonCallApi, @NonNull EditText editTextQuery,
      @NonNull TextView textViewResponse, @NonNull TextView textViewTitle,
      @NonNull TextView textViewTotalCalories) {
    this.rootView = rootView;
    this.buttonCallApi = buttonCallApi;
    this.editTextQuery = editTextQuery;
    this.textViewResponse = textViewResponse;
    this.textViewTitle = textViewTitle;
    this.textViewTotalCalories = textViewTotalCalories;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCaloriecountingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCaloriecountingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_caloriecounting, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCaloriecountingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonCallApi;
      Button buttonCallApi = ViewBindings.findChildViewById(rootView, id);
      if (buttonCallApi == null) {
        break missingId;
      }

      id = R.id.editTextQuery;
      EditText editTextQuery = ViewBindings.findChildViewById(rootView, id);
      if (editTextQuery == null) {
        break missingId;
      }

      id = R.id.textViewResponse;
      TextView textViewResponse = ViewBindings.findChildViewById(rootView, id);
      if (textViewResponse == null) {
        break missingId;
      }

      id = R.id.textViewTitle;
      TextView textViewTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewTitle == null) {
        break missingId;
      }

      id = R.id.textViewTotalCalories;
      TextView textViewTotalCalories = ViewBindings.findChildViewById(rootView, id);
      if (textViewTotalCalories == null) {
        break missingId;
      }

      return new ActivityCaloriecountingBinding((RelativeLayout) rootView, buttonCallApi,
          editTextQuery, textViewResponse, textViewTitle, textViewTotalCalories);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
