// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.GridLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAdminFuncBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final CardView approveleavesCard;

  @NonNull
  public final CardView dataCard;

  @NonNull
  public final GridLayout gridLayout;

  @NonNull
  public final CardView inventoryCard;

  @NonNull
  public final CardView logoutCard;

  @NonNull
  public final TextView textView;

  @NonNull
  public final View topView;

  private ActivityAdminFuncBinding(@NonNull RelativeLayout rootView,
      @NonNull CardView approveleavesCard, @NonNull CardView dataCard,
      @NonNull GridLayout gridLayout, @NonNull CardView inventoryCard, @NonNull CardView logoutCard,
      @NonNull TextView textView, @NonNull View topView) {
    this.rootView = rootView;
    this.approveleavesCard = approveleavesCard;
    this.dataCard = dataCard;
    this.gridLayout = gridLayout;
    this.inventoryCard = inventoryCard;
    this.logoutCard = logoutCard;
    this.textView = textView;
    this.topView = topView;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAdminFuncBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAdminFuncBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_admin_func, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAdminFuncBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.approveleavesCard;
      CardView approveleavesCard = ViewBindings.findChildViewById(rootView, id);
      if (approveleavesCard == null) {
        break missingId;
      }

      id = R.id.dataCard;
      CardView dataCard = ViewBindings.findChildViewById(rootView, id);
      if (dataCard == null) {
        break missingId;
      }

      id = R.id.gridLayout;
      GridLayout gridLayout = ViewBindings.findChildViewById(rootView, id);
      if (gridLayout == null) {
        break missingId;
      }

      id = R.id.inventoryCard;
      CardView inventoryCard = ViewBindings.findChildViewById(rootView, id);
      if (inventoryCard == null) {
        break missingId;
      }

      id = R.id.logoutCard;
      CardView logoutCard = ViewBindings.findChildViewById(rootView, id);
      if (logoutCard == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.top_view;
      View topView = ViewBindings.findChildViewById(rootView, id);
      if (topView == null) {
        break missingId;
      }

      return new ActivityAdminFuncBinding((RelativeLayout) rootView, approveleavesCard, dataCard,
          gridLayout, inventoryCard, logoutCard, textView, topView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
