// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPaymentBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final TextView creditcardRedirect;

  @NonNull
  public final TextView payableamt;

  @NonNull
  public final Button paymentbtn;

  @NonNull
  public final TextView textView5;

  @NonNull
  public final EditText upiid;

  private ActivityPaymentBinding(@NonNull ConstraintLayout rootView, @NonNull CardView cardView,
      @NonNull TextView creditcardRedirect, @NonNull TextView payableamt,
      @NonNull Button paymentbtn, @NonNull TextView textView5, @NonNull EditText upiid) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.creditcardRedirect = creditcardRedirect;
    this.payableamt = payableamt;
    this.paymentbtn = paymentbtn;
    this.textView5 = textView5;
    this.upiid = upiid;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPaymentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPaymentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_payment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPaymentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.creditcardRedirect;
      TextView creditcardRedirect = ViewBindings.findChildViewById(rootView, id);
      if (creditcardRedirect == null) {
        break missingId;
      }

      id = R.id.payableamt;
      TextView payableamt = ViewBindings.findChildViewById(rootView, id);
      if (payableamt == null) {
        break missingId;
      }

      id = R.id.paymentbtn;
      Button paymentbtn = ViewBindings.findChildViewById(rootView, id);
      if (paymentbtn == null) {
        break missingId;
      }

      id = R.id.textView5;
      TextView textView5 = ViewBindings.findChildViewById(rootView, id);
      if (textView5 == null) {
        break missingId;
      }

      id = R.id.upiid;
      EditText upiid = ViewBindings.findChildViewById(rootView, id);
      if (upiid == null) {
        break missingId;
      }

      return new ActivityPaymentBinding((ConstraintLayout) rootView, cardView, creditcardRedirect,
          payableamt, paymentbtn, textView5, upiid);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
