// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCreditcardpaymentBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final EditText cardholdername;

  @NonNull
  public final EditText cardnumber;

  @NonNull
  public final EditText cvv;

  @NonNull
  public final EditText expirydate;

  @NonNull
  public final TextView loginRedirectText;

  @NonNull
  public final Button signupButton;

  @NonNull
  public final TextView signupName;

  @NonNull
  public final TextView textView5;

  private ActivityCreditcardpaymentBinding(@NonNull ConstraintLayout rootView,
      @NonNull CardView cardView, @NonNull EditText cardholdername, @NonNull EditText cardnumber,
      @NonNull EditText cvv, @NonNull EditText expirydate, @NonNull TextView loginRedirectText,
      @NonNull Button signupButton, @NonNull TextView signupName, @NonNull TextView textView5) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.cardholdername = cardholdername;
    this.cardnumber = cardnumber;
    this.cvv = cvv;
    this.expirydate = expirydate;
    this.loginRedirectText = loginRedirectText;
    this.signupButton = signupButton;
    this.signupName = signupName;
    this.textView5 = textView5;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCreditcardpaymentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCreditcardpaymentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_creditcardpayment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCreditcardpaymentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.cardholdername;
      EditText cardholdername = ViewBindings.findChildViewById(rootView, id);
      if (cardholdername == null) {
        break missingId;
      }

      id = R.id.cardnumber;
      EditText cardnumber = ViewBindings.findChildViewById(rootView, id);
      if (cardnumber == null) {
        break missingId;
      }

      id = R.id.cvv;
      EditText cvv = ViewBindings.findChildViewById(rootView, id);
      if (cvv == null) {
        break missingId;
      }

      id = R.id.expirydate;
      EditText expirydate = ViewBindings.findChildViewById(rootView, id);
      if (expirydate == null) {
        break missingId;
      }

      id = R.id.loginRedirectText;
      TextView loginRedirectText = ViewBindings.findChildViewById(rootView, id);
      if (loginRedirectText == null) {
        break missingId;
      }

      id = R.id.signup_button;
      Button signupButton = ViewBindings.findChildViewById(rootView, id);
      if (signupButton == null) {
        break missingId;
      }

      id = R.id.signup_name;
      TextView signupName = ViewBindings.findChildViewById(rootView, id);
      if (signupName == null) {
        break missingId;
      }

      id = R.id.textView5;
      TextView textView5 = ViewBindings.findChildViewById(rootView, id);
      if (textView5 == null) {
        break missingId;
      }

      return new ActivityCreditcardpaymentBinding((ConstraintLayout) rootView, cardView,
          cardholdername, cardnumber, cvv, expirydate, loginRedirectText, signupButton, signupName,
          textView5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
