// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityCustHealthinfoBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button button2;

  @NonNull
  public final EditText editTextText2;

  @NonNull
  public final EditText editTextText3;

  @NonNull
  public final EditText editTextText4;

  @NonNull
  public final RadioButton female;

  @NonNull
  public final RadioButton male;

  @NonNull
  public final RadioGroup radioGroup;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final TextView textView4;

  @NonNull
  public final TextView textview6;

  private ActivityCustHealthinfoBinding(@NonNull ConstraintLayout rootView, @NonNull Button button2,
      @NonNull EditText editTextText2, @NonNull EditText editTextText3,
      @NonNull EditText editTextText4, @NonNull RadioButton female, @NonNull RadioButton male,
      @NonNull RadioGroup radioGroup, @NonNull TextView textView2, @NonNull TextView textView4,
      @NonNull TextView textview6) {
    this.rootView = rootView;
    this.button2 = button2;
    this.editTextText2 = editTextText2;
    this.editTextText3 = editTextText3;
    this.editTextText4 = editTextText4;
    this.female = female;
    this.male = male;
    this.radioGroup = radioGroup;
    this.textView2 = textView2;
    this.textView4 = textView4;
    this.textview6 = textview6;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityCustHealthinfoBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityCustHealthinfoBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_cust_healthinfo, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityCustHealthinfoBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button2;
      Button button2 = ViewBindings.findChildViewById(rootView, id);
      if (button2 == null) {
        break missingId;
      }

      id = R.id.editTextText2;
      EditText editTextText2 = ViewBindings.findChildViewById(rootView, id);
      if (editTextText2 == null) {
        break missingId;
      }

      id = R.id.editTextText3;
      EditText editTextText3 = ViewBindings.findChildViewById(rootView, id);
      if (editTextText3 == null) {
        break missingId;
      }

      id = R.id.editTextText4;
      EditText editTextText4 = ViewBindings.findChildViewById(rootView, id);
      if (editTextText4 == null) {
        break missingId;
      }

      id = R.id.female;
      RadioButton female = ViewBindings.findChildViewById(rootView, id);
      if (female == null) {
        break missingId;
      }

      id = R.id.male;
      RadioButton male = ViewBindings.findChildViewById(rootView, id);
      if (male == null) {
        break missingId;
      }

      id = R.id.radioGroup;
      RadioGroup radioGroup = ViewBindings.findChildViewById(rootView, id);
      if (radioGroup == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.textView4;
      TextView textView4 = ViewBindings.findChildViewById(rootView, id);
      if (textView4 == null) {
        break missingId;
      }

      id = R.id.textview6;
      TextView textview6 = ViewBindings.findChildViewById(rootView, id);
      if (textview6 == null) {
        break missingId;
      }

      return new ActivityCustHealthinfoBinding((ConstraintLayout) rootView, button2, editTextText2,
          editTextText3, editTextText4, female, male, radioGroup, textView2, textView4, textview6);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
