// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.GridLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTrainerFuncBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final CardView applyLeaveCard;

  @NonNull
  public final CardView clientDataCard;

  @NonNull
  public final GridLayout gridLayout;

  @NonNull
  public final CardView logoutCard;

  @NonNull
  public final TextView textView;

  @NonNull
  public final View topView;

  @NonNull
  public final CardView viewProfileCard;

  private ActivityTrainerFuncBinding(@NonNull RelativeLayout rootView,
      @NonNull CardView applyLeaveCard, @NonNull CardView clientDataCard,
      @NonNull GridLayout gridLayout, @NonNull CardView logoutCard, @NonNull TextView textView,
      @NonNull View topView, @NonNull CardView viewProfileCard) {
    this.rootView = rootView;
    this.applyLeaveCard = applyLeaveCard;
    this.clientDataCard = clientDataCard;
    this.gridLayout = gridLayout;
    this.logoutCard = logoutCard;
    this.textView = textView;
    this.topView = topView;
    this.viewProfileCard = viewProfileCard;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTrainerFuncBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTrainerFuncBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_trainer_func, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTrainerFuncBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.applyLeaveCard;
      CardView applyLeaveCard = ViewBindings.findChildViewById(rootView, id);
      if (applyLeaveCard == null) {
        break missingId;
      }

      id = R.id.clientDataCard;
      CardView clientDataCard = ViewBindings.findChildViewById(rootView, id);
      if (clientDataCard == null) {
        break missingId;
      }

      id = R.id.gridLayout;
      GridLayout gridLayout = ViewBindings.findChildViewById(rootView, id);
      if (gridLayout == null) {
        break missingId;
      }

      id = R.id.logoutCard;
      CardView logoutCard = ViewBindings.findChildViewById(rootView, id);
      if (logoutCard == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.top_view;
      View topView = ViewBindings.findChildViewById(rootView, id);
      if (topView == null) {
        break missingId;
      }

      id = R.id.viewProfileCard;
      CardView viewProfileCard = ViewBindings.findChildViewById(rootView, id);
      if (viewProfileCard == null) {
        break missingId;
      }

      return new ActivityTrainerFuncBinding((RelativeLayout) rootView, applyLeaveCard,
          clientDataCard, gridLayout, logoutCard, textView, topView, viewProfileCard);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
