// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPostfeedbackBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final Button buttonsubmit;

  @NonNull
  public final EditText editTextQuery;

  @NonNull
  public final TextView textViewTitle;

  private ActivityPostfeedbackBinding(@NonNull RelativeLayout rootView,
      @NonNull Button buttonsubmit, @NonNull EditText editTextQuery,
      @NonNull TextView textViewTitle) {
    this.rootView = rootView;
    this.buttonsubmit = buttonsubmit;
    this.editTextQuery = editTextQuery;
    this.textViewTitle = textViewTitle;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPostfeedbackBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPostfeedbackBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_postfeedback, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPostfeedbackBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonsubmit;
      Button buttonsubmit = ViewBindings.findChildViewById(rootView, id);
      if (buttonsubmit == null) {
        break missingId;
      }

      id = R.id.editTextQuery;
      EditText editTextQuery = ViewBindings.findChildViewById(rootView, id);
      if (editTextQuery == null) {
        break missingId;
      }

      id = R.id.textViewTitle;
      TextView textViewTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewTitle == null) {
        break missingId;
      }

      return new ActivityPostfeedbackBinding((RelativeLayout) rootView, buttonsubmit, editTextQuery,
          textViewTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
