// Generated by view binder compiler. Do not edit!
package com.example.powerup.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.powerup.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class InvitemBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final TextView tvEquipmentName;

  @NonNull
  public final TextView tvManufacturer;

  @NonNull
  public final TextView tvQuantity;

  private InvitemBinding(@NonNull CardView rootView, @NonNull TextView tvEquipmentName,
      @NonNull TextView tvManufacturer, @NonNull TextView tvQuantity) {
    this.rootView = rootView;
    this.tvEquipmentName = tvEquipmentName;
    this.tvManufacturer = tvManufacturer;
    this.tvQuantity = tvQuantity;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static InvitemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static InvitemBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.invitem, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static InvitemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.tvEquipmentName;
      TextView tvEquipmentName = ViewBindings.findChildViewById(rootView, id);
      if (tvEquipmentName == null) {
        break missingId;
      }

      id = R.id.tvManufacturer;
      TextView tvManufacturer = ViewBindings.findChildViewById(rootView, id);
      if (tvManufacturer == null) {
        break missingId;
      }

      id = R.id.tvQuantity;
      TextView tvQuantity = ViewBindings.findChildViewById(rootView, id);
      if (tvQuantity == null) {
        break missingId;
      }

      return new InvitemBinding((CardView) rootView, tvEquipmentName, tvManufacturer, tvQuantity);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
